version: '3.1'

services:
    generator:
        build:
            context: .
        image: hpinsley/generator
        ports:
            - 8080:80

    mail:
        image: mailhog/mailhog
        ports:
            - 8025:8025
